"""split_warm_profiles_target

Revision ID: 4b40e60ac715
Revises: e625379c6f99
Create Date: 2025-07-03 16:20:13.366573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b40e60ac715'
down_revision: Union[str, None] = 'e625379c6f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Создаем тип ENUM
device_type_enum = postgresql.ENUM('DESKTOP', 'MOBILE', 'TABLET', name='devicetype')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем тип ENUM перед использованием
    device_type_enum.create(op.get_bind())

    op.add_column('profiles', sa.Column('device_type', sa.Enum('DESKTOP', 'MOBILE', 'TABLET', name='devicetype'), nullable=False))
    op.add_column('server_configs', sa.Column('warm_desktop_profiles_target', sa.Integer(), nullable=True))
    op.add_column('server_configs', sa.Column('warm_mobile_profiles_target', sa.Integer(), nullable=True))
    op.drop_column('server_configs', 'warm_profiles_target')
    op.add_column('user_domain_settings', sa.Column('device_type', sa.Enum('DESKTOP', 'MOBILE', 'TABLET', name='devicetype'), nullable=False))
    op.add_column('user_keywords', sa.Column('device_type', sa.Enum('DESKTOP', 'MOBILE', 'TABLET', name='devicetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_keywords', 'device_type')
    op.drop_column('user_domain_settings', 'device_type')
    op.add_column('server_configs', sa.Column('warm_profiles_target', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('server_configs', 'warm_mobile_profiles_target')
    op.drop_column('server_configs', 'warm_desktop_profiles_target')
    op.drop_column('profiles', 'device_type')

    # Удаляем тип ENUM
    device_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
