"""Add device type support to profiles and settings

Revision ID: 51bf77f2fc8d
Revises: 4b40e60ac715
Create Date: 2025-07-03 16:28:13.152414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bf77f2fc8d'
down_revision: Union[str, None] = '4b40e60ac715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
