"""create strategy_proxy table

Revision ID: 5f3ddffa0a69
Revises: 77a1aeb5024b
Create Date: 2025-07-16 16:58:23.639811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f3ddffa0a69"
down_revision: Union[str, None] = "77a1aeb5024b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy_proxies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("total_uses", sa.Integer(), nullable=True),
        sa.Column("successful_uses", sa.Integer(), nullable=True),
        sa.Column("failed_uses", sa.Integer(), nullable=True),
        sa.Column("success_rate", sa.Integer(), nullable=True),
        sa.Column("response_time", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["strategy_proxy_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["user_strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Создаем индексы для улучшения производительности
    op.create_index(
        "ix_strategy_proxies_strategy_id",
        "strategy_proxies",
        ["strategy_id"],
        unique=False,
    )
    op.create_index(
        "ix_strategy_proxies_host_port",
        "strategy_proxies",
        ["host", "port"],
        unique=False,
    )
    op.create_index(
        "ix_strategy_proxies_status", "strategy_proxies", ["status"], unique=False
    )
    op.create_index(
        "ix_strategy_proxies_source_id", "strategy_proxies", ["source_id"], unique=False
    )

    # Добавляем уникальный индекс для предотвращения дублирования прокси в рамках одной стратегии
    op.create_index(
        "ix_strategy_proxies_unique_per_strategy",
        "strategy_proxies",
        ["strategy_id", "host", "port"],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_strategy_proxies_unique_per_strategy", table_name="strategy_proxies"
    )
    op.drop_index("ix_strategy_proxies_source_id", table_name="strategy_proxies")
    op.drop_index("ix_strategy_proxies_status", table_name="strategy_proxies")
    op.drop_index("ix_strategy_proxies_host_port", table_name="strategy_proxies")
    op.drop_index("ix_strategy_proxies_strategy_id", table_name="strategy_proxies")
    op.drop_table("strategy_proxies")
    # ### end Alembic commands ###
