# docker/prometheus/prometheus.yml
# Prometheus конфигурация с VNC метриками
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "vnc_alerts.yml"

scrape_configs:
  # Основное приложение
  - job_name: 'parser-backend'
    static_configs:
      - targets: [ 'backend:8000' ]
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Системные метрики
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  # PostgreSQL метрики
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  # Redis метрики
  - job_name: 'redis-exporter'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  # VNC специфичные метрики
  - job_name: 'vnc-metrics'
    static_configs:
      - targets: [ 'backend:8000' ]
    metrics_path: '/admin/debug/metrics'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]

